# Generated by Django 3.2.7 on 2021-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregister',
            name='phone',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Telefon raqam'),
        ),
    ]
